const express = require('express');
const router = express.Router();
const crypto = require('crypto');

const Validator = require('../models/validatorModel');
const Check = require('../models/checkModel');
const CheckResult = require('../models/checkResult');

/**
 * Middleware to Authenticate Validators using their ValidatorKey
 */
const authenticateValidator = async (req, res, next) => {
    // We expect the validator to send its key in the Headers
    const apiKey = req.headers['x-validator-key'];
    
    if (!apiKey) {
        return res.status(401).json({ message: "Unauthorized: Missing x-validator-key header." });
    }

    try {
        const validator = await Validator.findOne({ validatorKey: apiKey });
        if (!validator) {
            return res.status(403).json({ message: "Forbidden: Invalid Validator Key." });
        }
        
        // Attach the validator to the request so subsequent controllers know who is checking
        req.validator = validator;
        next();
    } catch (err) {
        return res.status(500).json({ message: "Internal server error during validator authentication" });
    }
};

/**
 * 1. Admin/Setup Route: Register a new Validator Node
 * This lets you easily generate testing nodes and grab their keys.
 */
router.post('/register', async (req, res) => {
    try {
        const { name, region } = req.body;
        
        // Generate a 64-character secure hexadecimal key natively
        const validatorKey = crypto.randomBytes(32).toString('hex');
        
        const validator = new Validator({
            name,
            region,
            validatorKey
        });
        
        await validator.save();
        
        res.status(201).json({ 
            message: "Validator Node successfully registered!", 
            name: validator.name,
            region: validator.region,
            validatorKey // Keep this strictly safe, the node uses it to auth!
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

/**
 * Heartbeat Route
 * Validators ping this to show they are active and ready.
 */
router.post('/heartbeat', authenticateValidator, async (req, res) => {
    try {
        req.validator.lastHeartbeat = new Date();
        await req.validator.save();
        res.status(200).json({ message: "Heartbeat ACK" });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

/**
 * 2. Validator Fetch Job Route
 * External nodes hit this route periodically to ask "What checks are pending?"
 */
router.get('/jobs', authenticateValidator, async (req, res) => {
    try {
        // Find checks generated by the scheduler that are still pending
        // And populate the monitor configuration so the node knows the target URL, Method, etc.
        const pendingChecks = await Check.find({ finalStatus: 'pending' })
            .populate('monitorId', 'url method expectedStatusCode timeoutMs') 
            .limit(10); // Batch size per fetch
            
        res.status(200).json({ jobs: pendingChecks });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

/**
 * 3. Validator Submit Results Route
 * After the node hits the target URL, it POSTs the results back here.
 */
router.post('/results', authenticateValidator, async (req, res) => {
    try {
        const { checkRoundId, monitorId, success, statusCode, responseTimeMs, errorMessage } = req.body;

        // Persist the specific node's report
        const result = new CheckResult({
            checkRoundId,
            monitorId,
            validatorId: req.validator._id,  
            region: req.validator.region,    // Sourced from auth token implicitly!
            success,
            statusCode,
            responseTimeMs,
            errorMessage,
            checkedAt: new Date()
        });

        await result.save();
        
        // Close out the check round (Mark 'up' or 'down' natively based on response payload)
        // We DO NOT change the Check consensus status here immediately.
        // We strictly leave it 'pending'. Our backend scheduler loop will safely
        // aggregate all results shortly based on majority consensus!

        res.status(201).json({ message: "Result verified and recorded successfully" });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;